### ISSUE TITLE
VPEEK doesn't support evaulation on the 2nd param

### ISSUE THREAD

**Issue by oziphantom** [commanderx16/x16-rom#1]
VPEEK(num,num) ; fine
VPEEK(var,var) ; fine
VPEEK(var+something, var) ; fine
VPEEK(anything,var+something); Syntax error
j= i + 3:VPEEK(anything,j) ; Bad Subscript Error

**Comment by mist64** [comment]
Can you try with r29? This should be fixed.

**Comment by oziphantom** [comment]
I'm on r29, it does seem to support some cases but not all...

**Comment by mist64** [comment]
In the laste example, the error is correct, since VPEEK is a function and you are using it as a statement.

**Comment by oziphantom** [comment]
it was a shortened example, 
but it seems there is something else going on... 
![image](https://user-images.githubusercontent.com/7146763/64474575-181a2680-d1ba-11e9-90e7-584b0dd04847.png)

**Comment by mist64** [comment]
Reproduced.

**Comment by mist64** [comment]
Minimal test case:

      PRINTVPEEK(0,0),VPEEK(11,0)

The second VPEEK is not tokenized. The encoded BASIC program contains the ASCII text "VPEEK".

**Comment by mist64** [comment]
Weird, now it doesn't reproduce any more!

**Comment by mist64** [comment]
Ah, this was fixed after the r29 release. It will be fixed in r30. In the meantime, try a newer [rom.bin.zip](https://github.com/commanderx16/x16-rom/files/3587511/rom.bin.zip).
