### ISSUE TITLE
GRAPH: GRAPH_move_rect overlap support

### ISSUE THREAD

**Issue by mist64** [commanderx16/x16-rom#111]
GRAPH_move_rect always copies the lines from top to bottom, which is incorrect if the two rectangles overlap and sy < ty.

A simple check should be made for this condition, and if it's true, a second code path should be used, which does the same as the original code path, but counts from the last line to the first line.

**Comment by gaekwad** [comment]
I tried submitting a pull request for this.  Still learning 6502 assembly and it seemed like a straight-forward issue to look at.

**Comment by mist64** [comment]
Fixed, thanks!
