### ISSUE TITLE
CHRIN not working ?

### ISSUE THREAD

**Issue by paulscottrobson** [commanderx16/x16-rom#119]
https://github.com/paulscottrobson/rpl-65/blob/master/source/core/extern.asm at 112 does not wait for keyboard input, and I have no idea what data its returning.

**Comment by BruceMcF** [comment]
I have no idea how the ca65 assembler parses input, but that routine is different from the others in its file in having opcodes concatenated to their label, where elsewhere labels are isolated on a line. If laid out as the rest of the code in that file:

[code]
ExternInput:
		lda 	#(InputBuffer & $FF)
		sta 	zTemp0
		lda 	#(InputBuffer >> 8)
		sta 	zTemp0+1
		lda 	#COL_WHITE
		jsr 	ExternColour
_EIRead:jsr 	$FFCF
		and 	#$7F
		cmp 	#13
		beq 	_EIExit
		sta 	(zTemp0)
		inc 	zTemp0
		bne 	_EIRead
		inc 	zTemp0+1
		bra 	_EIRead
_EIExit:lda 	#0
		sta 	(zTemp0)
		lda 	#13
		jsr 	ExternPrint
		rts
[/code]

Would be: [code]
ExternInput:
		lda 	#(InputBuffer & $FF)
		sta 	zTemp0
		lda 	#(InputBuffer >> 8)
		sta 	zTemp0+1
		lda 	#COL_WHITE
		jsr 	ExternColour
_EIRead:
		jsr 	$FFCF
		and 	#$7F
		cmp 	#13
		beq 	_EIExit
		sta 	(zTemp0)
		inc 	zTemp0
		bne 	_EIRead
		inc 	zTemp0+1
		bra 	_EIRead
_EIExit:
		lda 	#0
		sta 	(zTemp0)
		lda 	#13
		jsr 	ExternPrint
		rts
[/code]

Other than that, as long as $FFCF holds until there is a key input, I don't see an issue except that the routine as written allows for an arbitrarily long line buffer where I would presume that the line buffer would actually be limited in extent, something like:
[code]
...
_EIRead:
		jsr 	$FFCF
		and 	#$7F
		cmp  #13
		beq 	_EIExit
		sta 	(zTemp0)
		inc 	zTemp0
		lda	zTemp0
		cmp	#BuffLength 
		bmi 	_EIRead
_EIExit:
		lda 	#0
		sta 	(zTemp0)
		lda 	#13
		jsr 	ExternPrint
		rts
[/code]

**Comment by paulscottrobson** [comment]
It doesn’t, Ffcf returns immediately and is getting screen data from somewhere, not sure where. Top line maybe. The code worked as a line input a couple of months back.

**Comment by BruceMcF** [comment]
Ah, I see what you are saying ... that's you up at the top of that code block, it's JSR FFCF that is not behaving as it was behaving before.

That's a worry, that's the routine I was going to borrow to upgrade my ACCEPT from it's current simple enter or rubout via CHRGET. It shouldn't work when running on the C64 Kernal and then break on the CX16 Kernel.

**Comment by paulscottrobson** [comment]
It did screen editing as in Basic on the first call and read characters on subsequent.

**Comment by greg-king5** [comment]
https://github.com/paulscottrobson/rpl-65/blob/0dbbd2650edf158bbfeedf8ac8771386fdd83e18/source/core/extern.asm#L19-L20
```as
lda 	#$02 ; set colour
sta 	713
```
That address can become obsolete at any time.  You should _print_ background, as well as foreground, color codes.

**Comment by paulscottrobson** [comment]
You’re a genius 😁

**Comment by paulscottrobson** [comment]
In my defence when I wrote this you couldn’t set the background colour that way😉

**Comment by mist64** [comment]
Does this mean this is resolved?

**Comment by paulscottrobson** [comment]
Probably. I was setting the default print background to black by writing to $713 ; at the time there was no other way to do so. I presume in doing so I changed something else. I will give it a check.

**Comment by paulscottrobson** [comment]
Yes, it works if I use chr(1)
