### ISSUE TITLE
Not related to the rom but x16

### ISSUE THREAD

**Issue by logo4poop** [commanderx16/x16-rom#12]
I made a small website for commanderx16 that has better mobile support and in my opinion looks nicer. Since I don't have a facebook I thought this would be the place. http://commanderx16.surge.sh/
Would anyone like to use this instead of what we have now?

**Comment by logo4poop** [comment]
@vii1 Why are you confused?

**Comment by mist64** [comment]
Off-topic – please use the Facebook group instead.
