### ISSUE TITLE
Installed High Memory

### ISSUE THREAD

**Issue by PeterCamilleri** [commanderx16/x16-rom#124]
The X16 is specified as having from 512K through 2048K of high banked RAM.

Is there a kernal call or configuration location available that will indicate how much memory is actually installed?

**Comment by gaekwad** [comment]
This might change in the future, but right now there is a variable at $255 that contains the number of banks, so you can calculate it from there.  For a kernal call you can set the carry flag and call $ff99 (memtop) and the number of banks will be in the A register.

**Comment by mist64** [comment]
Just fixed the documentation bug; it's now correctly documented in the Programmer's Reference Guide.
