### ISSUE TITLE
r35 - Linux - MON no longer scrolls

### ISSUE THREAD

**Issue by Usoilworker** [commanderx16/x16-rom#125]
When using MON I am no longer able to scroll thru memory with the cursor up/down.
Using the F3 F5 keys as described in the instructions executes Load/save.

**Comment by mist64** [comment]
This is a work-in-progress branch to allow the monitor to auto-scroll again: https://github.com/commanderx16/x16-rom/tree/monitor_scrolling2

It's tricky, because previously, the monitor tapped into lots of internal KERNAL state, but now it has to go through APIs everywhere.
