### ISSUE TITLE
Unwanted ISO mode switching in r35

### ISSUE THREAD

**Issue by EgonOlsen71** [commanderx16/x16-rom#126]
This should output black text on a light grey background...which it does. But it also switches to ISO mode, which I don't think it should do:

```
PRINT CHR$(144);CHR$(1);CHR$(155);CHR$(1);"YEAH"
```

If I do the same thing with, for example, pink on light grey, no switch to ISO mode happens:

```
PRINT CHR$(150);CHR$(1);CHR$(155);CHR$(1);"YEAH"
```

A similar assembly routine has the same effect:

```
*=$2000

LDA #$90
JSR $FFD2
LDA commanderx16/x16-emulator#1 
JSR $FFD2
LDA #$9B
JSR $FFD2
LDA commanderx16/x16-emulator#1 
JMP $FFD2
```

**Comment by mist64** [comment]
Fixed by #114
