### ISSUE TITLE
Feature Request: Combined Microsoft V2.0 & C128 Style LOCATE

### ISSUE THREAD

**Issue by BruceMcF** [commanderx16/x16-rom#128]
This is inspired by a discussion at David Murray's Murray^2 site: https://murray2.com/threads/easiest-to-read-and-write-way-to-position-the-cursor-on-x16-basic.587/

Basic V2.0 offered LOCATE x,y to locate the cursor at a spot on the text display. C128 Basic V7.0 offers LOCATE x,y to place the virtual cursor at the x,y position on the graphical display.

I don't know whether any of the graphical commands would benefit from offering the C128 semantics,  but text mode programming would definitely benefit from offering the Microsoft V2.0 semantics.

Supporting ten Horizontal tabstops and four vertical tabstops at 8/16/24/32/40/48/56/64/72 and 80 for <Tab> and <VTab> would get partway there, but LOCATE is more efficient.

PLOT in the Kernel already gives support for the text mode version, and it seems that the graphical character routines have location built-in.

So the simplest solution would be to simply export access to PLOT, using the C128 LOCATE token but implement a Microsoft 6502 V2.0 style text mode LOCATE x,y.

**Comment by Starsickle** [comment]
Even if such a feature were to simply substitute for this code: 

```
1100 REM //SUBROUTINE - LOCATE
1101 REM // CALL BY SET LY%, LX% AND THEN GOSUB
1102 POKE $30D,LY% : POKE $30E,LX% : SYS $FFF0
1103 RETURN
```

I think it'd be helpful to have a LOCATE keyword that functions both in characters and pixels. Additionally, one could reduce calls to it if it would increment the cursor position by itself instead of requiring a new call.

**Comment by mist64** [comment]
See #227 for thoughts on whether it should be row,col or col,row.
