### ISSUE TITLE
Glitchy mouse cursor on Reset

### ISSUE THREAD

**Issue by ekmett** [commanderx16/x16-rom#139]
commanderx16/x16-emulator#247 appears to be a ROM issue.

```
MOUSE1:RESET
```

Fixing the behavior from the command line:

```
MOUSE0
```

or 

```
POKE $780,0:SYS $FF68
```

fixes the issue from the command line. From a quick scan of the kernal, during reset (`cint_legacy` is my working guess) we don't call `mouse_config` to turn the mouse back off (or just turn off the right bit in msepar) but do reinitialize VERA. `msepar` is still left masked as having the mouse on, so `mouse_scan` updates the sprite position and toggles the sprite back on during the interrupt giving the garbage cursor observed in that ticket.

I'd write a patch but I don't know anything about the legacy code placement issues documented in the `cint_legacy` source file.

**Comment by mist64** [comment]
Confirmed.

**Comment by mist64** [comment]
This reproduces with r38, but does not reproduce with the current HEAD of the emulator and ROM repositories.
