### ISSUE TITLE
New DATA logic breaks PROG.BAS

### ISSUE THREAD

**Issue by mist64** [commanderx16/x16-rom#14]
The new FROG.BAS demo fails with SYNTAX ERROR IN 720 with https://github.com/commanderx16/x16-rom/pull/8merged.

https://github.com/commanderx16/x16-demo/pull/14

@Frank-Buss

**Comment by Frank-Buss** [comment]
There is something strange happen with the minus sign, I will look at it.

**Comment by Frank-Buss** [comment]
Fixed in https://github.com/commanderx16/x16-rom/pull/19
