### ISSUE TITLE
PLOT sets and return coordinates in wrong registers

### ISSUE THREAD

**Issue by Dooshco** [commanderx16/x16-rom#145]
When calling kernel function PLOT ($FFF0), The Commander X16 Emulator R.37 uses wrong regsiters. It sets and returns Row in Register X and Column in Register Y. I believe it is more intuitive to use X for Columns and Y for Rows and I think C64 is using it that way but documentation out there is not consistent.
Also kernel function SCREEN returns width in X and height in Y so we have inconsistency in X16 ROM as well.

**Comment by greg-king5** [comment]
> When calling Kernel function PLOT ($FFF0), The Commander X16 Emulator R.37 uses the wrong registers. It sets and returns Row in Register X and Column in Register Y.

That behavior is correct.  The function was designed for efficient use by machine language on Commodore computers.  For example, after calling PLOT, a program can poke a character into the current location in (Commodore's) Video RAM simply by doing:
```asm
sta (PNT),y
```
(`PNT` is a Kernal variable that holds a pointer to the beginning of the current text line.)

**Comment by Dooshco** [comment]
That makes sense, thanks for explanation. I will close this Issue.
