### ISSUE TITLE
Initialize CBDOS vars on boot

### ISSUE THREAD

**Issue by rossato** [commanderx16/x16-rom#149]
At boot time, Kernal (ROM version r37) zeroes out the zero page and $0200 page, but leaves the CBDOS variables starting at bank 0, $AC00 unchanged.  This can lead to problems reading from the SD card, performing a warm reboot, and then trying to read again:

```
LOAD "$"

SEARCHING FOR $
B*
   PC  IRQ  BK AC XR YR SP NV#BDIZC
.;03A3 0000 00 33 E0 00 E2 ..**..**
.M 01E0 01FF
.:01E0 C2 95 C1 02 04 FF 33 91
.:01E8 C1 CB 02 00 68 D1 C4 DA
.:01F0 13 D9 CB 02 04 58 FB B7
.:01F8 DD 1D C9 C9 01 01 73 DF
```
Note that $C191 is two after the brk at @no_bufs, indicating that buf_alloc is out of buffers.

This can be worked around by poking zero to the CBDOS "initialized" variable at $BE8C before further SD card operations.  I believe the RAM initialization routine should do at least this much, possibly zero out the entire first bank of high RAM.

**Comment by rossato** [comment]
This might already be resolved by the pull requests from @theelkmechanic.  Feel free to close if this issue is no longer relevant.

**Comment by mist64** [comment]
This is probably fixed by now. a76615447ad8775ced664e15756cf2d7824eeec9 fixed a problem with initialization; though the current code is very different. The routine `reset_dos` will clear all state, and it is called once for every new SD card.
