### ISSUE TITLE
Update README.md for chargen.

### ISSUE THREAD

**Issue by rsbohn** [commanderx16/x16-rom#15]
Now that chargen is included in rom.bin it needs to be documented in README.md.

**Comment by mist64** [comment]
The emulator documentation has already been updated, and there it no need to document it in the ROM documentation. What am I missing?

**Comment by rsbohn** [comment]
* banked ROM ($C000-$DFFF):
	* bank 0: BASIC
	* bank 1: UTIL (monitor)
	* bank 2: DOS

bank 4: chargen?

**Comment by rsbohn** [comment]
This is fixed and now closed.
