### ISSUE TITLE
Enhance BASIC with ampersand routines

### ISSUE THREAD

**Issue by StewBC** [commanderx16/x16-rom#151]
It would be nice to have an easy system to "enhance" BASIC with something like the Applesoft Ampersand.  See this excerpt from "Enhancing Applesoft using ampersand routines" by Douglas B Eamon.

Applesoft BASIC's ampersand (&) jump feature gives the programmer an easy and fast way to connect machine language routines to BASIC. When the Applesoft interpreter encounters an "&," it does an immediate and unconditional jump to location $3F5 (decimal 1013). This feature, originally described as being "intended for the computer's internal use only" and "not a proper APPLESOFT command" (Apple Computer, 1978, p. 123), has become the favorite procedure for executing machine language routines from a running Applesoft program. Location $3F5 and the 2 bytes that follow are known as the ampersand jump vector. Since the location is in RAM, it can be easily modified; that is, it is possible to place into these locations a IMP (jump) to any location in memory. If the new location contains a machine language routine followed by an RTS (return from subroutine), the routine will be executed and return control to the Applesoft statement following the "&."

Example of how this is used:  Dr. Marc A. Golombeck has developed a Double Low Resolution graphics amper-library.  The Double Low-Resolution Amper Library includes a host of routines including:
&GR: switches to double LORES mode and clears the screen
&TEXT: returns to 40-column text mode
&COLOR=: sets the plotting color (range: 0..15)
&PLOT X,Y[,COLOR]:plots a pixel at X,Y. The parameter COLOR is optional.
&SCRN(X,Y,C%): reads out MAIN or AUX memory depending on the given coordinates and returns the color value C% of the selected pixel (range: $00..$0F / 0..15)
&VLIN Y1,Y2,X[,COLOR]: plots a vertical line from Y1 to Y2 at column X. The parameter COLOR is optional.
&HLIN X1,X2,Y[,COLOR]: plots a horizontal line from X1 to X2 at row Y. The parameter COLOR is optional.
There are libraries that deal with things that couldn't have been envisioned, such as networking.  It's a great way to keep BASIC relevant.

**Comment by greg-king5** [comment]
> It would be nice to have an easy system to "enhance" BASIC with something like the Applesoft Ampersand.

We have that feature!  Do you remember the "Commodore DOS Wedge"?  That's how it works.  The Commander X16 inherited the C64's BASIC interpreter.  It has two ways to extend the language.

As a program is scanned, the "BASIC Wedge" method looks for various trigger characters, and jumps to machine language code that handles the rest of a statement.

I call the second one the "interpreter hooks" method.  It's an extension of Kernal's hooks.  The ROM code calls through various hook pointer variables (depending on what the interpreter is doing).  User-supplied machine language routines can add keyword tokens to BASIC.  They're interpreted in the same way that the built-in tokens are handled -- as both commands and functions.  It is how BASIC extension cartridges work.

---
It would be nice if someone relocated the DOS Wedge for use on the Commander X16.

**Comment by Marrin** [comment]
It would be nice to have that in the kernal instead of the DOS command because that @ is sooo familiar from sooo many extensions starting with the Commodore DOS Wedge, over different freezer cartridges, and then the modern storage devices from CMDs HDD to SD card devices.

**Comment by mist64** [comment]
As @greg-king5 said, BASIC already has this, you can extend it with any statements and functions, and no prefixes are required. The simplest way is to hook the `IGONE` vector at $0308/$0309, save `TXTPTR`, use `CHRGET` to get characters from the stream, compare them with your keyword, and if it's not it, restore `TXTPTR` and jump to where the vector was originally pointing.

If you want to do it properly, you add a tokenizer (`ICRNCH`) and detokenizer (`IQPLOP`), too.

See https://www.pagetable.com/c64ref/c64mem/ for more info.
