### ISSUE TITLE
Feature Request: disk "boot loader" and metadata

### ISSUE THREAD

**Issue by bobbyjim** [commanderx16/x16-rom#159]
"Boot loader":

If I recall, the newer Commodore drives supported a "boot loader" from track 1, sector 0.

Call this a frivolous thing, but it might be nice to have an autoloader, in one of two ways:
- a search at a specific location, e.g. track 1, sector 0, for a key string or -whatever-
- or, a search for a specific file name.  

The latter is perhaps less "intrusive" / more "intuitive".

"Metadata":

Even more frivolous is a small record that explains the disk image layout.  Probably useless.

**Comment by tomxp411** [comment]
I think there was a plan to support an "autoexec.prg" or something of the sort. This would allow you to boot to a menu, which you could use to navigate the drive or launch a selection of programs.

**Comment by bobbyjim** [comment]
That's a reasonable and well-understood solution.

**Comment by mist64** [comment]
Dup'ing to #190.
