### ISSUE TITLE
Feature Request: Stuff Keyboard Buffer API

### ISSUE THREAD

**Issue by tomxp411** [commanderx16/x16-rom#164]
Requested Feature: Insert characters into the keyboard buffer. 

Use Cases: I'm working on a menu program, and I want to load a program from the BASIC screen by pre-populating a LOAD and RUN command on the screen, then stuffing two Carriage Returns into the keyboard buffer. (This ensures a clean LOAD with no leftover variables or data from the menu.)

I don't need a BASIC command do this, but having a documented KERNAL call would be enough. Ideally, simply placing the keystroke in the Accumulator, then calling the KERNAL routine. 

This means we should also have additional parameters on the SYS command to pass in A, X, and Y, or the ZP address to pick up the register values should be well documented (alongside the scratch registers at $02.)

Example:
100 CLS
110 PRINT "{DOWN 2}LOAD ";CHR$(34);"COOLGAME.PRG"
120 PRINT "{DOWN 2}RUN"
130 SYS {stuff},$0D
140 SYS {stuff},$0D
150 END

**Comment by mist64** [comment]
`kbdbuf_put` ($FEC3)

Example:
`POKE$30C,$4D:SYS$FEC3:POKE$30C,$53:SYS$FEC3`
