### ISSUE TITLE
VPOKE, VPEEK does not work correctly R38

### ISSUE THREAD

**Issue by SerErris** [commanderx16/x16-rom#167]
Hi if you put in the following code, it does not work as expected:
```
10120 VPOKE 1,$F000+I,VPEEK(0,$F800+I)
```
The above statement is a part of a loop to move the CHARROM to another addressspace in VRAM.

However it does not copy to $1F000 - instead it copies to $0F000. It looks like the VPOKE does not set the address correctly in this example and keeps the MSB at what is given in the VPEEK instruction.

This code for example works, but there should be really no difference between both versions.
``` 
10115 BT=VPEEK(0,$F800+I)
10120 VPOKE 1,$F000+I,BT
```

Example code to demonstrate (you can see the result on the screen):
```
10000 :REM SETUP SCREEN SCALING 2X = 320X240
10010 POKE $9F2B,64:POKE $9F2A,64
10020 COLOR 1,0:PRINT CHR$(147);
10030 REM SETUP BITMAP MODE 8BPP AND BITMAP START $4000
10040 POKE $9F2F,$20:POKE $9F2D,$07:POKE $9F29,PEEK($9F29) OR $10
10100 :REM MOVE CHARROM
10110 FOR I=0 TO $7FF
10120 VPOKE 1,$F000+I,VPEEK(0,$F800+I)
10130 NEXT
10140 POKE $9F36,$F8
```

**Be aware the last command in this example scrambles the CHARROM as it is not where it is expected and carries  random data. So you will not be able to see anything anymore. ...** 

Working code
```
10000 :REM SETUP SCREEN SCALING 2X = 320X240
10010 POKE $9F2B,64:POKE $9F2A,64
10020 COLOR 1,0:PRINT CHR$(147);
10030 REM SETUP BITMAP MODE 8BPP AND BITMAP START $4000
10040 POKE $9F2F,$20:POKE $9F2D,$07:POKE $9F29,PEEK($9F29) OR $10
10100 :REM MOVE CHARROM
10110 FOR I=0 TO $7FF
10115 BT=VPEEK(0,$F800+I)
10120 VPOKE 1,$F000+I,BT
10130 NEXT
10140 POKE $9F36,$F8
```

**Comment by Jaxartes** [comment]
The bug is still there (as of mid-2021).  There's a related problem in VPEEK().  Example:
```
VPOKE0,$C000,0
VPOKE1,$C000,1
?VPEEK(1,$C000+VPEEK(0,$C000))
A=$C000+VPEEK(0,$C000):?VPEEK(1,A)
```
The two outputs should both be "1" but the first is "0" instead.
