### ISSUE TITLE
f4a5.load.s - STY vs STA

### ISSUE THREAD

**Issue by Zakero** [commanderx16/x16-rom#171]
https://github.com/commanderx16/x16-rom/blob/9498437e4baf39b75a36b158f98f0ef9a59b4978/kernal/open-roms/iostack/f4a5.load.s#L33

The surrounding code makes me wonder if the "sty" should actually be "sta".

The intention looks like MEMUSS is being copied to STAL.  In kernelstatus_reset, the A register is set to #$00 so "MEMUSS+1" is not being used there.  Which leads me to believe that line 33 should be "sta" but I do not fully understand the details and could be wrong.

**Comment by greg-king5** [comment]
You aren't wrong.  It should be a simple 16-bit (two-byte) copy from `MEMUSS` to `STAL`.
