### ISSUE TITLE
RDTIM is incorrect

### ISSUE THREAD

**Issue by paulscottrobson** [commanderx16/x16-rom#177]
According to the docs RDTIM returns the clock time in AXY (e.g. A MSB), but the ROM returns it in YXA

**Comment by JimmyDansbo** [comment]
Looks like x16 kernal does exactly the same as the kernal in C64. Both a opposite of the documentation I have found.
Here is a small basic program to read the clock using RDTIM, try it on both the X16 and C64 and you should get the same result:

**Comment by paulscottrobson** [comment]
I looked at the ROM disassembly. You're right. 

The X16 documents don't say, and every reference I found either didn't say explicitly or did say A was the MSB of the jiffy clock. They must've all copied the error from each other. I can see the sense in having A as the LSB.
