### ISSUE TITLE
TI$ seems to overwrite last used string

### ISSUE THREAD

**Issue by mist64** [commanderx16/x16-rom#178]
The following code prints two identical values in each line:
```
10 A$=TI$
20 PRINT TI$,A$: GOTO20
```

It seems TI$ doesn't allocate a new string but takes the last used one and overwrites it?

(Thanks to @fvdhoef)

**Comment by Jaxartes** [comment]
Pull-request #219 fixes this.  The problem seems to have been _where_ the buffer was.  The buffer used by TI$ crossed over a boundary and wasn't recognized as temporary.
