### ISSUE TITLE
Building on mac

### ISSUE THREAD

**Issue by Gdsimms** [commanderx16/x16-rom#18]
Attempting to build on MacOS 10.14.6, macports cc65

* ca65 does not include subdirectories by default. I had to add "-Ikernal" to the kernal build line, "-Ibasic" and "-Imonitor" to the appropriate build lines. 
* I get this error for the monitor build line:
`ca65 -g -Imonitor -DMACHINE_X16=1 -DCPU_65C02=1 monitor/monitor.s -o monitor/monitor.o
monitor/monitor.s(899): Error: Unexpected end of line
monitor/monitor.s(900): Error: Unexpected trailing garbage characters
monitor/monitor.s(901): Error: Unexpected trailing garbage characters
make: *** [all] Error 1
`

FYI: 
`ca65 --version`
`ca65 V2.13.3 - (C) Copyright 1998-2012 Ullrich von Bassewitz`

**Comment by hasenbanck** [comment]
It seems that the version of cc65 in macport is totaly outdated. The current stable release is v2.18 and 2.13.3 was released in 2012. Homebrew seems to have 2.18 and personaly I can verify that the current head works fine on Mojave.
