### ISSUE TITLE
Potential out of bounds problem in BASIC

### ISSUE THREAD

**Issue by fvdhoef** [commanderx16/x16-rom#181]
In X16 BASIC there is a constant 'buflen' defined with a value of 89. But there is a 'buf' variable declared with .res 2*40+1
I think this .res should also be 'buflen' in size?

**Comment by Kroc** [comment]
This is a historical artefact; the VIC20 supported BASIC lines up to three screen lines of 22 characters (plus terminator), or 89 bytes. The same buffer exists for the C64, but it can only use 2 screen lines, so 80 bytes, plus terminator.

**Comment by fvdhoef** [comment]
Ah, that makes sense. But I assume that you mean _four_ screen lines? 22*3+1 is only 67. 22*4+1=89
