### ISSUE TITLE
Kernal jump table entry for kbdbuf_get_modifiers

### ISSUE THREAD

**Issue by stefan-b-jakobsson** [commanderx16/x16-rom#182]
Hi,

The function kbdbuf_get_modifiers in kernal/kbdbuf.s returns what keyboard modifiers are used (e.g. Shift, Ctrl, Alt, AltGr).

This is of great value, as there are some overlaps when reading the keyboard with the GETIN function.

With overlaps I mean for instance that the GETIN return value is the same for the Esc key as for Ctrl+c.

kbdbuf_get_modifiers would, however, need its own Kernal jump table entry, so that the call address remains the same between ROM updates.

**Comment by mist64** [comment]
`kbdbuf_get_modifiers` ($FEC0)
