### ISSUE TITLE
Welcome To 2021^W2022, Copyright needs to be updated

### ISSUE THREAD

**Issue by Loganh4005** [commanderx16/x16-rom#186]
^^^ Yup!

**Comment by irmen** [comment]
almost 2022 now :partying_face:

**Comment by Loganh4005** [comment]
> almost 2022 now 🥳

Ironically yeah

**Comment by mist64** [comment]
Update it where?

**Comment by mist64** [comment]
This fixed the year in the emulator help printout: https://github.com/commanderx16/x16-emulator/commit/d326917648c52b8263dece02bf2118c9d42cf9ec
