### ISSUE TITLE
Auto-boot from SD

### ISSUE THREAD

**Issue by kktos** [commanderx16/x16-rom#190]
Right now, the computer is going straight to basic.
Could we have a boot sequence with the basic as the default part to start ?

The obvious would be to boot on sdcard; loading and running a system file (e.g. X16.SYS).
But as there will be extension cards which can handle devices, it could also be interesting to have a boot mechanism here too.

I don't know for the C64 but on the apple //, we can boot on any cards. Pretty handy.

**Comment by mist64** [comment]
This should definitely be a feature of the first shipping hardware.

**Comment by mist64** [comment]
C65 documentation, for reference:

```
BOOT -- Load and execute a program

    BOOT
    BOOT SYS
    BOOT filename [,Bbank] [,Paddress] [,Ddrive] [<ON|,>Udevice]

BOOT  without a filename given causes the computer to look for a BASIC
program  called  AUTOBOOT.C65* on the indicated diskette,  LOAD it and
RUN it (just like RUN "AUTOBOOT.C65*").

BOOT with a filename given will cause the executable binary file to be
BLOADed and executed beginning at the load address.  If a load address
is  not  given,  the  file  will  be loaded and execution begun at the
address stored on disk.

BOOT  SYS is a special command that copies the "home" sector (the very
track  and  sector) of the C64DX built-in drive into memory at address
$400 to $5FF  (one physical sector,  512 bytes)  and perform a machine
language  JSR  (Jump  SubRoutine)  to it.  It has the same function as
turning  on  your C64DX while holding down the ALT key.  It is used to
boot  an alternate operating system from either a CBM 3.5" diskette or
an  MSDOS (720K) diskette.  If used in a BASIC program,  and it fails,
the  system  can  be corrupted. BOOT SYS does *not* use the normal DOS
to access the disk.

        BOOT            Loads & runs BASIC program called
                        AUTOBOOT.C65* on system disk.

        BOOT U9         Loads & runs BASIC program called
                        AUTOBOOT.C65* on disk unit 9.

        BOOT "ml"       Load & executes machine language
                        program called ML, starting at address
                        stored on disk.
```

**Comment by mist64** [comment]
I can think of two major use cases:
* A game/application SD card/disk can autostart the game/application.
* The user puts an autostart script on the main SD card to set up the keyboard layout, screen colors etc.

So this is what we should do IMO:
* Add `BOOT` BASIC statement.
* The same codepath will be run on RESET.
* The file to be loaded is `AUTOBOOT.X16*`
* It has to be a $0801-style PRG with a BASIC header.
