### ISSUE TITLE
LOAD does not correctly honor ,1 flag

### ISSUE THREAD

**Issue by tomxp411** [commanderx16/x16-rom#192]
I've discovered that when LOADing a BASIC program written on the Commodore 128 (and presumably the PET), the program always loads back to $1C01, even if I do not use ,1 when loading the program.

for example:
```
  LOAD "TEST1.PRG",8
  SEARCHING FOR TEST1.PRG
  LOADING FROM $1C01 TO $1C35
  READY.
```  

I would expect the above example to load to $0801, regardless of the start address in the file, since I did not append ,1 to the LOAD command.

The bug came up as part of this discussion on the forum: 
https://www.commanderx16.com/forum/index.php?/topic/1197-how-to-detect-commander-x16-basic-vs-eg-commodore/#comment-8880

**Comment by greg-king5** [comment]
See Pull Request #173.

**Comment by mist64** [comment]
Fixed on master.
