### ISSUE TITLE
Default joystick doesn't work.

### ISSUE THREAD

**Issue by paulscottrobson** [commanderx16/x16-rom#194]
repeat
a = sys(&FF53)
locate 0,0:print sys(&ff56)
until false

Whether in BASIC or Assembler appears to return $00 until any keyboard key is pressed, after which it behaves correctly. Faulty initialisation ?

**Comment by kktos** [comment]
Paul, did you try it with the "new hardware" rom & emulator ? the code for joystick handling was changed.

**Comment by paulscottrobson** [comment]
Nope same with current repos. Suspect initialise problem - Joystick status is updated on receipt of messages from PS/2 keyboard, but some initial value is not copied. Might work in CBM Basic but that probably loads text via buffer stuffing.

**Comment by mist64** [comment]
I'm using the following BASIC code:
```
REM 10 SYS$FF53
20 POKE$30C,0:SYS$FF56
30 PRINTCHR$($93)
40 PRINTBIN$(255-PEEK($30D));BIN$(255-PEEK($30C))
50 GOTO 20
```
(The result is the same whether line 10 is enabled or not – the default interrupt controller calls this 60 times per second anyway.)

I cannot reproduce the problem with the current HEADs in the x16-emulator and x16-rom repositories. With a "Nimbus" bluetooth joystick paired with macOS 12.2 and x16emu started with `-bas test.bas -joy1`, I get the correct bit patterns.

**Comment by mist64** [comment]
Oh, you mean the *keyboard* joystick emulation, not an actual gamepad? Yes, this is intended. Until the first key is pressed on the keyboard, we don't know whether a keyboard is even connected to the X16. That's why the API returns all 1 bits, which indicates that the requested joystick is not present.

**Comment by mist64** [comment]
That said, a test shows that actually, before any key is pressed, .Y should be $FF, but it's $00.
