### ISSUE TITLE
BASIC function $bdcd (print positive number) not working?

### ISSUE THREAD

**Issue by jeroenjacobs79** [commanderx16/x16-rom#196]
Hi,

Seems ~~KERNAL~~ BASIC function (print positive integer) is not working?

The following code works on my C64:

```
*=$0801 "BASIC stub"

line1:  .word next, 2021
        .byte $9e
        .byte $20
        .text toIntString($0840)
        .byte 0

next:   .word 0


*=$0840 "Program start"

ldx #5
lda #0
jsr $bdcd
/* wait for input before exit */
jsr $ffcf
rts

```

But it doesn't seem to work on X16 emulator? Getting no output at all, and the READY prompt is back at the top of the screen. (Snippet is KickAss assembler syntax)

I can attach the PRG file itself if you want.

**Comment by jeroenjacobs79** [comment]
Gonna close this again, I assumed all C64 KERNAL functions were supported, but it only supports functions $FF81 and above.

**Comment by jeroenjacobs79** [comment]
Re-opening again as this is a BASIC ROM feature, so it should be supported, no?

**Comment by kktos** [comment]
hum, I don't think so. there is a sort of jump table with "well known" addresses, coming from C64, yes. But that's all.

**Comment by kktos** [comment]
Found the vectors:
https://github.com/commanderx16/x16-rom/blob/master/kernal/vectors.s

**Comment by jeroenjacobs79** [comment]
Maybe I'm just misunderstanding things here, but the documentation says that X16 is compatible with C64 BASIC, and function $bdcd is a BASIC ROM function, no? So it should work?

**Comment by mist64** [comment]
Compatible with C64 BASIC means it will run C64 BASIC programs, not: support all JSRs into the BASIC implementation. For once, the X16 memory layout is different, so BASIC can't be located at $A000-$BFFF like on the C64.

What we have though is BASIC's floating point library extracted and accessible through a stable jump table at $FE00 on bank 4:

https://github.com/commanderx16/x16-rom/blob/master/fplib/jumptab.s

With this, it's easy to get the same behavior as $bdcd, if you just use the code from the C64 ROM to call into floating point functions:

https://www.pagetable.com/c64ref/c64disasm/#BDCD

**Comment by jeroenjacobs79** [comment]
@mist64 Hi, thank you very much for clarifying this :)

**Comment by mist64** [comment]
It's now also documented in the PRG:

https://github.com/commanderx16/x16-docs/blob/master/Commander%20X16%20Programmer's%20Reference%20Guide.md#floating-point-library
