### ISSUE TITLE
jsrfar can't be nested

### ISSUE THREAD

**Issue by mist64** [commanderx16/x16-rom#20]
Since jsrfar uses the zero page location savbank, nested invocations will break because they overwrite the saved bank.

**Comment by lgblgblgb** [comment]
I guess some can write an JSRFAR routine which pushes the current bank number into the stack then the address of JSRRTS routine (by keeping mind the JSR return address in stack speciality of 65xx CPUs ...) into the stack, then setting the desired bank and JMP'ing the desired routine there. Then the called routine can just return with RTS, so JSRRTS (which probably in KERNAL so always there) gets the control, pop back the old bank from stack, set old bank up, and then RTS opcode (so the original caller of the JSRRTS routine gets back the control). If I am right here, this exists only in my mind right now ... Bonus: the JSRFAR'red routine can simply return with RTS. That routine can be called by either JSRFAR or regular FAR, and both cases work. Using stack ensures the possibility of nesting. Disadvantage: precious stack page usage ...

**Comment by vii1** [comment]
Opened a draft #35 to start working on this.

**Comment by BruceMcF** [comment]
If JSRFAR stacks savbank and then puts the target bank in savbank, then the bank register, then calls the target routine address, on return it can pop the former savbank, put it in savbank and the bank register, then return.

The only alternative to using the hardware stack is to create a software stack, and then you are either slowing it down and increasing index register usage or really slowing it down and increasing zero page usage. Done as above, you simply need to document that a jsrfar require 5 bytes on the return stack ... two for the return to the calling routine, one to nest the bank, two for the return to jsrfar from the called routine.

**Comment by BruceMcF** [comment]
The cleanest solution is if savbank is reserved for processes that won't further modify via1porta and for jsrfar to stack the contents of via1porta and leave savbank alone.

Something along the lines of:
    STA TA: STY TY: STX TX
    PHP: PLX
    PLA: STA v: PLA: STA v+1
    LDA via1porta: PHA
    LDY #3: LDA (v),Y: STA via1porta
    DEY: LDA (v),Y: STA jv+1: DEY: LDA (v),Y: STA jv
    PHX: LDA TA: LDY TY: LDX TX: PLP: JSR +
    STA TA: STY TY: PHP: PLY: PLA: STA viaporta
    PHY: LDY TY: LDA TA: PLP: RTS:
+  JMP (jv)

(note that a bank of pseudo-registers would be a touch faster, it saves storing to temporary storage locations heading toward the call and saves restoring to registers returning from the call)

**Comment by mist64** [comment]
I'm confused. I've long changed the code to not use savbank any more. And I think I can be correctly nested now.

**Comment by BruceMcF** [comment]
> I'm confused. I've long changed the code to not use savbank any more. And I think I can be correctly nested now.

Then it seems like you could close your issue.
