### ISSUE TITLE
JSRFAR to RAM BANK clobbers P

### ISSUE THREAD

**Issue by CasaDeRobison** [commanderx16/x16-rom#209]
In kernal/drivers/x16/memory.s there are 8 lines (154-161 as I write this):

    lda $0104,x
    sta rom_bank    ;restore ROM bank
    lda $0103,x     ;overwrite reserved byte...
    sta $0104,x     ;...with copy of .p
    plx
    pla
    plp
    plp

This restores the original ROM BANK prior to JSRFAR call, then overwrites the reserved byte with a copy of P, then restores all the earlier saved registers.

In inc/jsrfar.inc are the equivalent lines for JSRFAR to RAM BANK:

    lda $0104,x
    sta ram_bank    ;restore RAM bank
    ; doesn't overwrite reserved byte with copy of P
    plx
    pla
    plp
    plp

Note that the lines to overwrite the reserved byte are missing, so the final plp results in clobbering the P register with the original RAM BANK.

**Comment by CasaDeRobison** [comment]
Restore P register on return from JSRFAR to RAM BANK #210

**Comment by mist64** [comment]
Good catch!
