### ISSUE TITLE
Feature Request: Loading headerless files

### ISSUE THREAD

**Issue by Elektron72** [commanderx16/x16-rom#211]
The kernal LOAD routine expects files to contain a two-byte header specifying the address at which they should be loaded. Although the LOAD routine can be instructed to load at an arbitrary address, it is impossible to load the first two bytes of a file as data using only this routine. This makes it difficult to handle file formats that do not include this header.

**Comment by ZeroByteOrg** [comment]
I concur. If you want to make a program that opens standard files such as .ZIP files, .VGM files, .WAV files, .BMP files, etc - then you're just SOL unless you roll your own loader from scratch.

**Comment by irmen** [comment]
You could do this already with some nasty code that goes like this

OPEN file
CHRIN 2 bytes, store them at given load address
CLOSE file
LOAD file at address+2
return load size + 2
