### ISSUE TITLE
stack looks corrupted in __jmpfr that ends up in bank 02 at address $c612

### ISSUE THREAD

**Issue by jeringa** [commanderx16/x16-rom#212]
I've been working on a debugger for 8bit systems and decided to add X16 (via the existing emulator).

I've got an issue where it crashes after a call to __jmpfr that ends up in bank 02 at address $c612. 
The stack look corrupted after what looks like an extra pull off the stack to the accumulator.

I have attached a copy of the trace. the problem appears at the end of the file. I realise it's probably an issue with my debugger :/
It's also worth noting that I haven't finished wiring up most of the hardware in the debugger (yet)

[trace.log](https://github.com/commanderx16/x16-rom/files/6446992/trace.log)

**Comment by greg-king5** [comment]
```
__jmpfr:         JMP   $02:c02d        ; 4c 2d c0 : abs    cc00    | abs[c02d]=4c                      A=01 X=00 Y=08 SP=f8 FLAGS=24 PC=02df - FLAGS=no1b dIZc - stack[f9]=ca,02
02:c02d:         JMP   $02:c612        ; 4c 12 c6 : abs    cc00    | abs[c612]=cd                      A=01 X=00 Y=08 SP=f8 FLAGS=24 PC=c02d - FLAGS=no1b dIZc - stack[f9]=ca,02
```
That first line is correct.  But, the second line should say
```
02:c02d:         JMP   $02:e1fe
```
`$02:$c612` is in the middle of a subroutine (it puts a character [pulled from the stack] into screen RAM).
