### ISSUE TITLE
Add KERNAL API to query current screen mode

### ISSUE THREAD

**Issue by mjallison42** [commanderx16/x16-rom#214]
The kernal call, SCREEN_SET_MODE, has no counterpart to obtain the current screen mode. 
The kernal var is not exposed.

Context: screen handling during breaks and program run in Codex Assy Env.

**Comment by stefan-b-jakobsson** [comment]
Yes, it would be nice if you could read the mode.

**Comment by irmen** [comment]
You can use the SCREEN routine to read the current number of columns and rows, but that's about it.
