### ISSUE TITLE
BASIC GET statement strange result

### ISSUE THREAD

**Issue by JustinBaldock** [commanderx16/x16-rom#218]
10 GET A
20 PRINT A
30 GOTO 10
On the X16 emulator R38 on Windows 10 PC this code will display -48 scrolling down screen unless a number is pressed on the keyboard. On the Commodore 64 the program displays 0 down the screen. If the variable A$ is used the output of nothing on the screen unless a key is pressed is the same on the X16 and C64.

So, appears to me a small bug on the X16? Suspect something about use of float/string variable type?

**Comment by Jaxartes** [comment]
Looks like when it tries to read a number, checking for "$" and "%" prefixes (hexadecimal and binary) makes it "forget" that it didn't get any character at all.

("finh" in [https://github.com/commanderx16/x16-rom/blob/master/basic/code17.s](url) clobbers the carry flag supplied by "chrget")

An experimental fix for the that seems to make "GET A" work ok.  Not sure whether what's the _right_ fix; needs testing.
