### ISSUE TITLE
Add RAM/VRAM memcpy

### ISSUE THREAD

**Issue by bobbyjim** [commanderx16/x16-rom#222]
GIVEN: There are two reasonably abstract sprite calls in the extended KERNAL.

1. Now that VERA has a PSG, it seems that EVENTUALLY the KERNAL could have a call or two to set up and play sounds.

2. It also seems reasonable (??) that EVENTUALLY the KERNAL could have a call to copy memory from system RAM into VRAM.  Or extend its current mem copy routine.

Because the KERNAL is an abstraction layer for "stuff", allowing implementations to vary without breaking code.

EXAMPLE 1.  The X8 has a different VERA access mechanism.  The KERNAL calls would disguise this to some degree.

EXAMPLE 2.  Some fool replaces VERA with VULKAN or something else.  He implements the KERNAL calls accordingly.  Code which uses the KERNAL might not care.

Example 2 is likely much trickier than I assume, but you get the idea.

**Comment by mist64** [comment]
* Copying into VRAM is indeed a common task, and since there's a regular memcpy already, this seems like a useful and consistent addition.
* As for sound, I am not convinced. There is nothing that KERNAL code could make *easier* (it's not any easier to call the KERNAL to set up registers than to POKEing into registers), and there is no way to properly abstract sound hardware without losing most of what it is capable of. There is PRINTCHR$(7). ;-)

**Comment by mist64** [comment]
I changed the title to reflect RAM/VRAM memcpy only.

**Comment by mist64** [comment]
There are currently three functions in the new memory API:
* `memory_fill`
* `memory_copy`
* `memory_crc`
The first two would benefit from supporting VRAM, the third one not so much.

Here some ideas:
1. Add a "bank" argument to the calls (for `memory_copy` two arguments), in e.g. the .X and .Y registers. 0 means RAM, $80 and $81 mean VERA banks 0 and 1. The functions then set the address registers and read from and write to the data port(s).
2. Pass one (or two for `memory_copy`) flags on whether to increment (source and) destination after each byte. The caller has to set up the VERA address registers (and the increment).
3. As above, plus magic: The functions compare source and destination addresses to the $9F00-$9FFF range, and if yes, they don't increment the addresses.

The third option has the advantage that this will also work with external hardware that has a VERA- (or VDC-)like data port.
