### ISSUE TITLE
Feature: LOCATE command

### ISSUE THREAD

**Issue by tomxp411** [commanderx16/x16-rom#227]
We need a BASIC command to set the cursor to a specific location. I suggest the LOCATE command as seen in Advanced BASIC, GWBASIC, and BASIC 7.

On the PC, the format is LOCATE [row][,col]. This allows you to do things like LOCATE 12 to set the cursor to row 12 without affecting the column. 

On Commodore BASIC 7, the format is LOCATE col, row. This is backward from the PC, but is more consistent with graphics commands, which all use the row,col coordinate system. 

A similar command, "SPOKE" has been suggested in the forum:  https://www.commanderx16.com/forum/index.php?/topic/2297-spoke-command/

**Comment by mist64** [comment]
Dup of #128.
