### ISSUE TITLE
MONITOR wraps around if ROM bank is > 7

### ISSUE THREAD

**Issue by stefan-b-jakobsson** [commanderx16/x16-rom#234]
It seems like the built-in MONITOR wraps around if the ROM bank specified with the O command is greater than 7.

If you enter "O08" and then display memory with "M C000" you get the contents of ROM bank 0, and so on.

I made a small test with ROM bank 8 populated: a small assembly program copying the contents of ROM bank 8 to RAM. It worked fine. So the problem must be within the MONITOR code.

The problem in the MONITOR code wasn't obvious to me when I looked at it briefly.

EDIT: It hit me that the monitor could be using KERNAL function FETVEC. And sure enough, there is an AND #7 in kernal/drivers/x16/memory.s line 214 that probably should be removed.

**Comment by mist64** [comment]
Thanks!
