### ISSUE TITLE
Discussion: Should Math lib FADDT, FMULTT, FDIVT and FPWRT be fixed?

### ISSUE THREAD

**Issue by mist64** [commanderx16/x16-rom#244]
The X16 Math library is compatible with the C128's:

* change: https://github.com/commanderx16/x16-rom/issues/231
* [documentation](https://github.com/commanderx16/x16-docs/blob/master/Commander%20X16%20Programmer's%20Reference%20Guide.md#math-library)

Problem: As I understand it, the calls `FADDT`, `FMULTT`, `FDIVT` and `FPWRT` of the original C128 API didn't work as expected and were useless. If you look at these subroutines in x16-rom/math/*.s, you'll see that they require the flags set up in a certain way, which a client can't reproduce without breaking the abstraction and reading some internal state of the library. Here's an article that explains the problem: [FADDT on c64-wiki.de](https://www.c64-wiki.de/wiki/FADDT); [English auto-translation](https://www-c64--wiki-de.translate.goog/wiki/FADDT?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en-US&_x_tr_pto=wapp)

I appended replacement calls `FADDT2`, `FMULTT2`, `FDIVT2` and `FPWRT2, which do the necessary setup, to the end of the jump table. Now I'm wondering whether I should replace the original calls with these instead. Given that they were probably never useful (or used!), it's safe (and clean) to replace them.

Input on this matter is very much appreciated!

(See also: [discussion on this topic in the forum](https://www.commanderx16.com/forum/index.php?/topic/2566-feedback-on-floating-point-math-library-requested/))

**Comment by irmen** [comment]
Prog8 doesn't call them, by luck.  I don't think I will ever call them, but if they're there and you have working alternatives already, I'm +0.1 for replacing the old ones.  (but aren't those used internally by BASIC ? will this not break BASIC?)

**Comment by mist64** [comment]
> (but aren't those used internally by BASIC ? will this not break BASIC?)

There are several exported symbols already that are "USED BY BASIC DO NOT CALL", and before I changed the order of the jumptable to be C128 compatible, that's what these four were marked as.
