### ISSUE TITLE
Add butterfly logo to the ROM charset

### ISSUE THREAD

**Issue by mist64** [commanderx16/x16-rom#251]
The ROM charset should have the butterfly logo somewhere.

* It's tricky with the PETSCII charset, since it should be compatible with previous computers from the Commodore line. Maybe add a way to change a character programmatically, and back.
* It's more relaxed with the ISO character set.

**Comment by bobbyjim** [comment]
Sprite data for the butterfly could live in one of the spare ROM banks... and a tiny routine to load it into VERA?

**Comment by mist64** [comment]
Maybe we should do this instead: In the Programmer's Reference Guide, in the section about the character sets, add a BASIC program that gets the location of the character set in VERA RAM and uses `READ` and `VPOKE` in a loop to overwrite a character with the reference butterfly `DATA`. (And the same in assembly.) This way, applications can easily have the logo if they need it.

**Comment by mist64** [comment]
The logo was added to the ISO charset as $AD in 8af34f4.
