### ISSUE TITLE
Host drives PS/2 data low before releasing clock

### ISSUE THREAD

**Issue by jburks** [commanderx16/x16-rom#270]
This was captured on a system running @ 4MHz. In order to remove ambiguities, the data line was disconnected from the PS/2 keyboard with only a weak (~12K ohm) pull-up resistor attached. The PS/2 data line is observed to be driven low for approximately 750 microseconds prior to the host releasing the clock line. Per "The PS/2 Mouse/Keyboard Protocol" document floating around the internet, this should be interpreted by the keyboard as a request by the host to send data to the keyboard:

> If the host wants to send data, it must first put the Clock
and Data lines in a "Request-to-send" state as follows:
> * Inhibit communication by pulling Clock low for at least 100 microseconds.
> * Apply "Request-to-send" by pulling Data low, then release Clock.

![DS1Z_QuickPrint16](https://user-images.githubusercontent.com/326088/163056443-426e018f-9572-4274-8243-01d0751bcd8f.png)

**Comment by mist64** [comment]
fc9c897c98d55666c4f05dde27bfbc9c9b8c9403
