### ISSUE TITLE
Codex build breaks full ROM build

### ISSUE THREAD

**Issue by jburks** [commanderx16/x16-rom#272]
The codex makefile as changed by #269 has no build rule for the `cx` target but lists it as a dependency for `all`. @mjallison42

**Comment by mist64** [comment]
```
(cd codex; make)
make[1]: *** No rule to make target `cx', needed by `all'.  Stop.
make: *** [build/x16/codex.bin] Error 2

```

**Comment by mist64** [comment]
Fixed by https://github.com/commanderx16/x16-rom/pull/273
