### ISSUE TITLE
SCREEN in R39 changes background color to blue and foreground color to white

### ISSUE THREAD

**Issue by mobluse** [commanderx16/x16-rom#281]
SCREEN has a new, undocumented side effect in R39: it also changes background color to blue and foreground color to white. This didn't happen before in e.g. R38. R39 behavior breaks compatibility with many of my R38 programs, but I can fix that. I still think it would be better if the colors were preserved as before, because then you can test different screen modes without having to change the colors.

At least two more on the forum also agrees to this: https://www.commanderx16.com/forum/index.php?/topic/2580-emulator-r39-released/&do=findComment&comment=18927

**Comment by mist64** [comment]
Settings the colors should only happen when switching into or out of graphics mode.
