### ISSUE TITLE
`SCREEN` BASIC command to switch screen modes

### ISSUE THREAD

**Issue by Kroc** [commanderx16/x16-rom#29]
_This is not a request to add this immediately :P Maybe someone will take this upon themselves to do._

Add a BASIC command to change screen modes without the need to poke/vpoke.

```
SCREEN cols, rows, [back-colour[, fore-colour]]
```

Specifying rows & columns would be preferable to actual pixel values as this provides better flexibility for the KERNAL / VERA to select actual output resolution more intelligently (e.g. imagine a later revision that supports 1080p)

**Comment by mist64** [comment]
I've added a `SCREEN` statement with a byte argument. The different KERNAL-supported modes have their unique numbers. This is not meant or useful for switching VERA modes in order to manually populate the screen contents afterwards, but to switch to a KERNAL-supported configuration.

Close?

**Comment by Kroc** [comment]
From the perspective of the BASIC user, who wishes to be abstracted from the VERA registers, yes
