### ISSUE TITLE
Support dead keys

### ISSUE THREAD

**Issue by mist64** [commanderx16/x16-rom#296]
Alt+E, E should print "É", but Alt+E currently does nothing.

**Comment by mobluse** [comment]
AltGr+E when SV-SE types € when in ISO mode. A dead key is e.g. if ' followed by e types é, then the ' is the dead key. In US International AltGr+Shift+E should type É, but in EurKEY, Ë. In EurKEY AltGr+Shift+G types É.

**Comment by mist64** [comment]
(The example with Alt+E, E) was the Apple US International keyboard, which I'm used to, but which isn't actually part of the X16's list. :))

**Comment by mobluse** [comment]
I was talking about Linux with X and Windows, since they have similar US International and EurKEY, but EurKEY is available for macOS, but I haven't tried it.
