### ISSUE TITLE
Question: is there a "correct" way to enhance the basic ?

### ISSUE THREAD

**Issue by kktos** [commanderx16/x16-rom#31]
Let's say I want to add a new command, how can I do it ?
For example, with Applesoft Basic, you can extend it with the & cmd;
it's a special token which call a ZP address where you can put your code.
Easy way to extend the basic without changing the ROM.
Is there something similar with this basic ?
Cheers.

**Comment by mist64** [comment]
It is done the same way as on all Commodore machines. The vector at 0304 is for tokenization, 0306 for detokenization, 0308 for instruction execution and 030A for function execution. This way, BASIC extensions can add first-class keywords without a special prefix. Numerous extensions like Simons' BASIC do this. This is the BASIC extension part of the Final Cartridge III:

https://github.com/mist64/final_cartridge/blob/master/core/basic.s

The commented C64 ROM source can be helpful to understand what's going on:

https://www.pagetable.com/c64disasm/
