### ISSUE TITLE
Request support for Basic program line renumbering

### ISSUE THREAD

**Issue by rpontual** [commanderx16/x16-rom#32]
I recommend adding a line renumbering program to the BASIC code. I suggest to implement using the syntax used on mBASIC, see attachment. This allows development and maintenance of a basic code while help maintaining the code structured (e.g. the line number 1000s to be used for I/O, etc).

During the renumbering process the line numbers referenced in GOTO and GOSUB statements should automatically be updated as well (e.g. if line number 34 is renumbered to 100 then "GOTO 34" should be updated to "GOTO 100"). This includes line numbers in implicit GOTO statements such as "IF A=1 THEN 55".
![10D02A7D-D9E8-440D-893B-FA88584B412D](https://user-images.githubusercontent.com/23462158/65387326-464c4a00-dd14-11e9-94fc-2792b5b53340.jpeg)

**Comment by jjgignac** [comment]
Why did you close this issue?  I've started working on a RENUM command.  Did the idea get rejected?

**Comment by jjgignac** [comment]
Never mind.  I see that it's a dupe.
