### ISSUE TITLE
SCREEN 6 line feed at bottom of screen inconsistent

### ISSUE THREAD

**Issue by kelli217** [commanderx16/x16-rom#326]
In the r41 release, in SCREEN 6, there's something anomalous about the automatic line feed that occurs when a character is output to the last character position on the screen. Just go into that screen mode and hold down any key that produces a character, until you reach the end of the screen, and observe the behavior.

Sometimes there will be a blank line, sometimes not. The previous lines also shift up and down in relationship to each other, occasionally creating two-line blank areas where previously there was only one blank line.

**Comment by mist64** [comment]
Dup of #319
