### ISSUE TITLE
RFE: ROM bank dedicated to lookup tables, for VERA note frequencies and perhaps other purposes

### ISSUE THREAD

**Issue by mooinglemur** [commanderx16/x16-rom#328]
I'm opening this issue mainly for discussion, as the idea has been casually mentioned in the Discord.

As it stands, VERA PSG takes a frequency value which linearly corresponds to Hz.  This requires a lookup table to translate from note-pitch values to frequency.  For the pure note values, this requires roughly a page of lookups.

However, if someone wants to do pitch bends/slides on VERA PSG and the YM2151 at the same time, the YM uses a logarithmic note/note-fraction based value, while VERA PSG uses a linear Hz value, requiring a large lookup table.

To store one octave's worth of 1/64 semitone step frequencies, matching the resolution of the YM2151, 768 values are required, or 1.5 KiB, which can be ROR/LSRed into lower octaves as needed.  If we wanted to cut the resolution to 1/16 semitone, we could use 192 values instead, or 1/20 of a semitone using 240 values.

I don't know:
* whether the powers that be are open to the idea of such a ROM bank
* the acceptable amount of duplication in such a bank to support saving CPU cycles for as many use cases as possible
* what everyone else would want in such a bank besides these freq lookups

Unfortunately, whatever is done here will likely need to be set in stone once it's in the bank.  Locations can't change without breaking code that uses of the values from the bank, so decisions for this would need careful consideration.

**Comment by irmen** [comment]
Currently I have to use floating point math to convert 
https://github.com/irmen/prog8/blob/master/examples/cx16/bdmusic.p8#L34

I could create a lookup table myself as the notes for this particular example are all in a table already, but I'd like a general solution too

**Comment by mooinglemur** [comment]
https://github.com/commanderx16/x16-rom/pull/376 closes this issue
