### ISSUE TITLE
GEOS won't start

### ISSUE THREAD

**Issue by maxgerhardt** [commanderx16/x16-rom#359]
I've built both the latest x16-rom (commit 5d8ba9f36b4c4fb4397b94c7ce273e2d4e5e0110) and x16-emulator https://github.com/commanderx16/x16-emulator/commit/e10bc7b7dfa20fa73a4bace58c956ef7805779d7) from source for Windows using MinGW64.

I'm pointing the emulator at the new ROM image and start it with 

```
x16emu.exe -rom C:\Users\Max\Desktop\cx16_dev\x16-rom\build\x16\rom.bin -geos
```

But all that appears is

![grafik](https://user-images.githubusercontent.com/26485477/200055321-e26774f0-f31b-4aeb-b90c-8c6980dd16f3.png)

Note that the self-built ROM works fine regularly (when not starting GEOS).

**Comment by mist64** [comment]
It needs the file manager on disk. Add `-sdcard APPS64.D64`.

**Comment by maxgerhardt** [comment]
Okay, that file doesn't seem to be included. Grabbing it from *somewhere* and adapting the command gives me the starting screen with an unmovable mouse.

![grafik](https://user-images.githubusercontent.com/26485477/200067558-97855e71-bb2e-47ff-8aa3-83f3b3ac08ef.png)

But now that's the same as tracked in https://github.com/commanderx16/x16-rom/issues/344?

**Comment by mist64** [comment]
Yes.
