### ISSUE TITLE
RFE: method for fetching the current working directory

### ISSUE THREAD

**Issue by mooinglemur** [commanderx16/x16-rom#370]
Right now we don't have a way to know the name of the directory we're in.  I don't think anything in the fat32 driver keeps the state either other than the cluster.  It appears to keep cwd_cluster, and without adding any additional state, we could find the name of it by traversing up one level and iterating over the entries to match the cluster number to the start lba of the dirent.

It seems CPU-inefficient to iterate, so perhaps we should store the name of the dirent found by find_dir within fat32_chdir.

This takes an entire page of kvars RAM, but I think this is useful.

We could poll the cwd through a special DOS filename (like "`$=C`" or something)?

**Comment by mooinglemur** [comment]
Perhaps we do need to iterate to find it.  If we started in `/a/b/c`, and we do `DOS"CD:.."`, if we go the route of saving the name, our cwd would now contain `..` instead of the directory name.  We need to find the name of the cwd by searching its parent directory.

**Comment by irmen** [comment]
Iterating to find it isn't bad imo because I don't think a program will call this often. So it's not bad if it takes a little time to determine the path.

**Comment by mooinglemur** [comment]
Some half-asleep-state pondering of this problem pointed to reusing the code path for doing directory listings.  Basically a request for the final portion of the cwd is, under the hood, a traversal up to the previous directory, and a listing with a filter.  That filter would be matching a currently-inaccessble attribute, which is the cluster number of where the directory starts.

If DOS is able to provide bread crumbs to user applications to construct a full path, this should be enough.

Just thinking out loud on this.  Perhaps we expose two new behaviors, or one behavior that satisfies both.
1) give user applications the ability to fetch the cwd's cluster number
2) give user applications the ability to get a directory listing that includes the cluster number for all directory entries, perhaps similar to the listing type that outputs the file time.

To combine these two, perhaps the cwd's cluster could be output at the top of this special-behavior directory listing.

**Comment by mooinglemur** [comment]
implemented by https://github.com/X16Community/x16-rom/pull/5
