### ISSUE TITLE
Can't get JSRFAR do to what I expect it to.

### ISSUE THREAD

**Issue by EgonOlsen71** [commanderx16/x16-rom#42]
I can't get JSRFAR to work in r32. The issue might very well be that I'm too stupid for it, but I really need some help with this. I made a little test case for r31 to do what DOS is actually doing:

```
*=$2000
LDA #$0
JSR $E6F5
RTS
```

That works just fine. So I made a r32-JSRFAR variant, which doesn't work. It looks like this:

```
*=$2000
LDA #$0
JSR $FF6E
; or JSR $03D1
.WORD $E736
.BYTE 7
RTS
```

I used to -debug option to understand what's going on, but I don't really know what to make of it. 

This is my code loaded and disassembled in the monitor (it starts at $2001 here, because at $2000 is the $FF to trigger the debugger. The jump to JSRFAR here is direct, see below): 
https://jpct.de/jsrfar-problem/code.png

This is the code at $FF6E (the address for the JSRFAR call) according to the monitor:
https://jpct.de/jsrfar-problem/ff63_expected.png

This is what comes up in the debugger when actually running the program with a call to $FF6E:
https://jpct.de/jsrfar-problem/ff63_actually.png

Maybe it's a debugger issue, but it puzzles me...anyway, I replaced the call to $FF6E with a call to $03D1. That executes the JSRFAR routine (not illustrated here). Then it jumps to $E736, where I expect to find the PTSTAT routine according to the rom.sym file). But the debugger tells me this:

https://jpct.de/jsrfar-problem/ptstat_actually.png

And all in all, it just doesn't work and I'm not sure why...

**Comment by mist64** [comment]
* You can only use `JSR $FF6E` while you're on bank 7. Otherwise, you have to use `JSR $03D1`.
* ptstat is a BASIC symbol at E736. You have to call it on bank 0, which is BASIC, but you are calling it on bank 7, which is KERNAL.

**Comment by EgonOlsen71** [comment]
I see. Is there any way to determine if a symbol is BASIC or KERNAL just by looking at the rom.sym? My mapping itself works, but obviously my assumptions which addresses go where are wrong.

**Comment by EgonOlsen71** [comment]
To clarify this a little bit: My assumption (ignore PTSTAT, that was an error on my side) was, that everything that's in the KERNAL on the C64 (like rnd for example) is in the KERNAL on the X16 as well. That's obviously not the case (rnd again...). That causes a problem to my automated mapping, because I just can't decide which goes where unless there's some way to tell...I accept crude ways as well...

**Comment by mist64** [comment]
If the address was below $E500 on the C64, it's BASIC, otherwise KERNAL. Does this help?

**Comment by mist64** [comment]
Unfortunately, I don't see a way to convince cc65 to know about banks. It supports the 65816, so I can specify 24 bit addresses in the linker .cfg file, but all references to symbols > $FFFF will then cause a "range error" when linking... How does this work when building for 65816?

**Comment by greg-king5** [comment]
> Unfortunately, I don't see a way to convince cc65 to know about banks. It supports the 65816, so I can specify 24-bit addresses in the linker .cfg file, but all references to symbols > $FFFF will then cause a "range error" when linking. How does this work when building for 65816?

65816 support is very incomplete.  The cc65 compiler's `__far__` keyword does nothing.  The ca65 assembler does support that CPU.  The ld65 linker tries to support ca65, but some things might be missing.

Can you show some of the lines that produce range errors?

**Comment by EgonOlsen71** [comment]
> If the address was below $E500 on the C64, it's BASIC, otherwise KERNAL. Does this help?

Yes, that helps. I was taking $E000 as an indicator before. Looks like I just have to replace that with $E500 then. I'll give it a try later...

**Comment by EgonOlsen71** [comment]
I couldn't get SAVE or LOAD to run by making direct calls to the KERNAL via JSRFAR. It looked fine when stepping through it in the debugger, but it didn't saved or load anything in the end. Anyway, I converted these calls to use the $FFxx-jumptable, which is better anyway and now it works. That leaves me with one JSRFAR call for outputting from error messages...and that one works fine now.
So my compiler now works with r32, thanks for helping me out.

**Comment by mist64** [comment]
The emulator hooks the jump table calls for LOAD and SAVE. It can't hook the locations of the implementations. That's one we should always use the jump table! ;-) – if there's an entry for what you need... :-P

**Comment by EgonOlsen71** [comment]
Thanks for the explanation...that makes sense.
