### ISSUE TITLE
[Feature Request] Support for FAT16 and FAT12 on the SD card

### ISSUE THREAD

**Issue by LRFLEW** [commanderx16/x16-rom#45]
I was experimenting with the `-sdcard` option in the emulator, and was struggling to get it working. I eventually figured out that, in the macOS tool Disk Utility, creating a "FAT32" disk image would create partitions of the type FAT16 or FAT12 if the image was small enough to use those formats. I'm guessing the reason it does that is that they use less space for the allocation table, and it's trying to provide the maximum possible amount of space for files. This makes it more challenging to make ISO files that work. While supporting FAT16 or FAT12 probably won't be an issue for physical cards, as most will be large enough to require FAT32 anyways, but supporting FAT16 and FAT12 could make it a lot easier to use disk images easier (both for using with the emulator, and for shared projects to be written directly to an SD card). Since all the FAT types are related, FAT16 and FAT12 should be able to reuse a lot of the existing code for FAT32, which would minimize the work required to support it (and the space it uses on the ROM).

**Comment by mist64** [comment]
The only use case would be saving on space in the emulator case. FAT32 has to be at least ~500 MB iirc, but this is a tiny amount for any computer that is powerful enough to run x16emu.
