### ISSUE TITLE
SWITCHER is broken

### ISSUE THREAD

**Issue by qbradq** [commanderx16/x16-rom#48]
[In the docs](https://github.com/commanderx16/x16-docs/blob/master/Commander%20X16%20Programmer's%20Reference%20Guide.md#other-new-features) the Switcher feature is described, and it used to work. However it seems to be broken on more recent builds.

Example from fresh pull and build of the emulator and ROM.
https://gfycat.com/meekweeewe
ROM version 8b1f368435848b607f3e939c85da295e83441167
Emulator version f3121f06c69283e18fa5421562dbc9f17c413d31

Expected Behavior captured on a fresh build at r31 (ROM and EMU):
https://gfycat.com/keencleverangelfish

**Comment by mist64** [comment]
This was fixed in d35aa0865be843ca5472cb698cd163e0ccd4363d
