### ISSUE TITLE
Feature Request: Kernel & Basic zero page usage "staying in their lanes"

### ISSUE THREAD

**Issue by BruceMcF** [commanderx16/x16-rom#56]
I was just warned that zero page location $02, one of the "free" zero page locations I was using in my C64 port of Camel Forth for Z80, is now taken over in the CX16 for keydown/keyup detection.

While there is a lot of zero page locations that may be used if Basic is not used, making machine language routines that can be using SYS calls is trickier. It is even trickier for a general purpose programming language which intended to reserve a small area at the lower end of Basic program space for small utility Basic programs as a shell programming language for file operations, if I do not know in advance what the SYS routine may be doing. Starting from the C64 Basic and Kernel memory maps, the CX16 should be adding two free spaces at $00/$01, making the free space in $02 particularly appealing for a doubly indirect jump vector, with $6C in $00 and the address vector in $01/$02.

But over and above that, in the C64 system, the KERNAL generally sticks to $90 to $FA and Basic sticks to $03 to $8F plus $FF. If Kernel functions are going to start to randomly use what were previously Basic locations, then the strategy of USING the zero page below $90 for assembly language programs which do NOT plan to inter-operate with Basic goes out the window.

Dropping the Datasette port should open up many or all of:
; ~ $92 Cassette timing constant
; ~ $96 Cassette block synchronization number
; ~ $9B/$9C Cassette parity byte / tape byte received flag
; ~ $9E/$9F Cassette read pass 1&2 error logs
; ~ $A5/$A6 Cassette sync byte counter / #chars in I/O buffer
; ~ $B0/$B1 Pointer to timer for cassette reads
; ~ $B2/$B3 Pointer to start of cassette buffer
; ~ $BE/$BF Cassette R/W duplicate block counter / ready byte register
; ~ $C0 Cassette motor On/Off flag

... if any of those are indeed not used by anything but Datasette support and have not yet been claimed by other Kernel functions, they should be the place to start allocating Kernel zero page locations.

Beyond that, there are a number of Kernel locations that are primarily IN the zero page to save a byte or two in the Kernel to squeeze it into 8K, but are not required for indirect address modes and are not used inside inner loops, and so do not in reality need to be in the zero page at all.

Indeed, Key Up/Down is an example of that: if the Kernel has already used up all of the locations available in $90 to $FA, then it is time to use Page 2 and 3 more heavily for things that are not priorities to place in the zero page ... and if/when those are used up, to go past the keycode table in Page 4 and grab page 5 for those general Kernel operations memory locations.

**Comment by kghultland** [comment]
I am having similar problems with my porting of durexforth, still struggling to get the
kernel to run properly. It temporary reuses a few addresses in the zero page that ought not to cause problems for the machine if they work and are used as they were in a C64 :)

BASIC RND function seed value ($8B, $8C, $8D, $8E)  
Tape Error Log ($9E, $9F)

**Comment by paulscottrobson** [comment]
It appears to be a fault in the build process (or it's already been corrected). The code overwriting $02 is in kernal/joystick.s, at the end, where it uses a zp location "j0tmp" which is allocated to segment "ZPKERNAL" which should be in the "lanes".

**Comment by BruceMcF** [comment]
I have no idea how that segmenting system works ... whether it could possibly wrap around on overflow if they have overflowed $FF. But there eventually needs to be a documented section of RAM that can be used by code called from Basic with SYS ... even if it is provided in a set of Basic locations that are not storing persistent data at the time of a SYS call ... and there needs to be SOME machine language routine ZP locations that can be used by userland interrupt routines no matter what the state of Basic may happen to be ... which is what $02 and $FB, $FC, $FD, $FE were for the C64.

**Comment by greg-king5** [comment]
> I have no idea how that segmenting system works ... whether it could possibly wrap around on overflow if they have overflowed $FF, and there are locations that BASIC hasn't put a claim on.

The linker (ld65) doesn't wrap-around; and, it doesn't overflow.  Instead, it complains that the memory area is too big.

**Comment by mist64** [comment]
I have been reworking all this. Branch https://github.com/commanderx16/x16-rom/tree/basic_geos has the following (rough) zero page allocation:
* $00-$7F available to the user
* $80-$8D used by the KERNAL
* $8E-$9E used by CBDOS
* $9F-$FF used by BASIC

**Comment by BruceMcF** [comment]
That's lovely ... with that ZP allocation, I could have my Forth return stack on the zero page while still allowing it to cooperate with Basic ... which is a big dividing line for C64 Forth models.
