### ISSUE TITLE
Kernal overwrites $02

### ISSUE THREAD

**Issue by paulscottrobson** [commanderx16/x16-rom#58]
According to the documentation, if you don't use BASIC, $00-$8F are available.

This is wrong. In the scan_to_joystick routine, called as part of the interrupt, the j0tmp is currently assigned the address $02 ; so the interrupt is randomly overwriting this byte (the address this happens is $F5BD, the routine starts at $F5CF)

**Comment by mist64** [comment]
https://github.com/commanderx16/x16-rom/branches is fixing this...

**Comment by mist64** [comment]
Can someone verify this in r33?

**Comment by paulscottrobson** [comment]
Still playing silly buggers on r33 but fixed in the repository.

**Comment by mist64** [comment]
Closing then!
