### ISSUE TITLE
KERNAL / BASIC should provide a built-in mouse cursor

### ISSUE THREAD

**Issue by Kroc** [commanderx16/x16-rom#64]
KERNAL / BASIC should provide a built in mouse-pointer / mouse-driver so that mouse properties, such as acceleration curve, left/right-handed-click are globally provided, avoiding multiple, conflicting mouse behaviours cropping up in homebrew software.

BASIC commands should be available to enable/disable the built-in mouse pointer and to read an mouse event-queue (much like the keyboard).

A default mouse pointer would be uploaded to VERA from the ROM, so that it can be easily redefined. Sprite no. 128 would probably be a good choice for the pointer.

_edit_ -- also, GEOS would be able to hook into this to minimize code/behaviour duplication between the systems.

**Comment by greg-king5** [comment]
> A default mouse pointer would be uploaded to VERA from the ROM, so that it can be easily redefined. Sprite no. 128 would probably be a good choice for the pointer.

A mouse pointer should be in front of everything else -- sprite number 1.

**Comment by Robert-Lloyd3** [comment]
This appears to be fixed in r34.
