### ISSUE TITLE
Support SD2IEC API in ROM?

### ISSUE THREAD

**Issue by Kroc** [commanderx16/x16-rom#7]
If the X16 ROM used the SD2IEC API for its SD-card access, it would make it much easier to get code working for both the C64 and Commander X16. Gregory Naçu put together all-in-one online documentation here: http://www.c64os.com/post/sd2iecdocumentation

**Comment by mist64** [comment]
Great link, thanks.

Since the SD card code has been written from scratch, we need to get the base API working first:
https://www.pagetable.com/?p=1038

**Comment by mist64** [comment]
Except for REL files, the CMDR-DOS now almost has feature parity with sd2iec, including subdirectories, partitions etc.

Close? Open specific bugs for missing features?
