### ISSUE TITLE
fatal: rom.bin doesn't work with emulator

### ISSUE THREAD

**Issue by Frank-Buss** [commanderx16/x16-rom#71]
I compiled the latest x16-rom and the latest x16-emulator, and tried the x16emu with the generated rom.bin, and all I see is a blue screen when starting the emulator.

**Comment by mist64** [comment]
I just did a fresh checkout on macOS 10.14 and I can't reproduce.

**Comment by Frank-Buss** [comment]
Hmm, works now, maybe I had some old files, sorry.
