### ISSUE TITLE
LOAD into VRAM does not work.

### ISSUE THREAD

**Issue by paulscottrobson** [commanderx16/x16-rom#72]
Using the script below to generate a file SPRITES.BIN, LOAD "SPRITES.BIN",1,3 does not load it into VRAM, it loads it into program RAM.  Experiments with the debugger show it is not getting as far as the modified loader routine.

spriteData = [ 0,0 ]
for y in range(0,64):
	for x in range(0,64,2):
		spriteData.append(y)
h = open("SPRITES.BIN","wb")
h.write(bytearray(spriteData))
h.close()

**Comment by oziphantom** [comment]
VLOAD not LOAD
