### ISSUE TITLE
Single colored line at bottom of visible area in SCREEN 128 mode

### ISSUE THREAD

**Issue by Robert-Lloyd3** [commanderx16/x16-rom#75]
Switching to SCREEN 128 mode leaves the 201st row of pixels visible towards the bottom of the screen, just outside the X coordinate range of 0-199. Anything displayed at this row in a previous SCREEN mode will remain visible when SCREEN 128 is activated. This row of remnant pixels cannot be written to once SCREEN 128 mode starts. (I haven't tried VPOKE'ing at it to make it go away.)

In a likely second but seemingly related issue, SCREEN 128 mode also leaves 40 pixels of black screen visible at the bottom of the display in the r34 emulator, reminiscent of APPLE ]['s HGR mode that left 4 rows of text at the bottom of the screen for use, but this area is not writable like the APPLE ]['s HGR mode. Leaving the area at the bottom of the display visible implies it can be used.

In this mode, Vera Layer 0's MODE 7 TILE-BASE register (start of bit mapped graphics display area) is set to $10000. With the available Vera RAM of $00000 - $1FFFF available, the 64K possible (barring any other allocations) will not allow for anything much over 320x200 (320x204, actually). I realize that with this memory allocation, the full 320x240 screen resolution will not be available, but can anything be done to hide the blacked-out section at the bottom of the display when using SCREEN 128?

**Comment by indigodarkwolf** [comment]
There's little to be done about the black area. It could be moved around some, but it can't be removed. See also the discussion here: https://www.commanderx16.com/forum/index.php?/topic/179-black-area-at-bottom-of-emulator/#comment-823

**Comment by mist64** [comment]
Confirmed that
`COLOR2,3:PRINTCHR$(147):SCREEN128`
will show a cyan-colored line between the visible area (200 lines of white) and the black area.

**Comment by mist64** [comment]
The code in kernal/drivers/x16/screen.s does this:

```
	lda #(400/2)
[...]
	pha
	lda #2
	sta VERA_CTRL
	pla
	sta VERA_DC_VSTOP
```

And this is the documentation of `DC_VSTOP`:

> **DC_HSTART**/**DC_HSTOP** and **DC_VSTART**/**DC_VSTOP** determines the active part of the screen. The values here are specified in the native 640x480 display space. HSTART=0, HSTOP=640, VSTART=0, VSTOP=480 will set the active area to the full resolution. Note that the lower 2 bits of **DC_HSTART**/**DC_HSTOP** and the lower 1 bit of **DC_VSTART**/**DC_VSTOP** isn't available. This means that horizontally the start and stop values can be set at a multiple of 4 pixels, vertically at a multiple of 2 pixels.

Not sure whether we're writing the wrong value, or whether the emulator is off by one.

**Comment by mist64** [comment]
Someone has to test this on real hardware. :)

**Comment by mist64** [comment]
The 320x200 mode was replace with 320x240, so this doesn't apply any more.
