### ISSUE TITLE
$8F (set PETSCII-UC even if ISO) should be printed first after reset

### ISSUE THREAD

**Issue by mobluse** [commanderx16/x16-rom#82]
I think $8F should be the first character printed after reset since this always sets PETSCII-UC and clears the screen if ISO was used before. (If it was not ISO before, the screen is not cleared, so it still needs $93, clear screen.) This might not be necessary for VERA, but it would be useful for external systems that listens to what is output on serial or filter programs that receive output from the emulator using `-echo raw`.

$8F could probably be added before $93 here:
https://github.com/commanderx16/x16-rom/blob/cba111f47e958d6b1ad6ebf850dfaad08edc7137/basic/init.s#L131

This was discussed here earlier: 
https://github.com/commanderx16/x16-emulator/pull/112#issuecomment-535721167

One could imagine that X16 has a console on the serial port at boot which is on until it is turned off by e.g. a program similar to autoexec.bat in MS-DOS. This would be useful for debugging or using X16 without a screen and keyboard. This console would be the same as the screen and keyboard since X16 is not a multiuser system.

**Comment by mist64** [comment]
I'd accept a pull request. :)
