### ISSUE TITLE
TIME/TI is always 0

### ISSUE THREAD

**Issue by mobluse** [commanderx16/x16-rom#84]
In the developing version `TIME`/`TI` is always 0.
Always:
```
?TI
 0
```
Normally `TI` gives different increasing values.

**Comment by mist64** [comment]
It seems BASIC doesn't recognize TI and TI$ in the expression evaluator any more.

**Comment by mist64** [comment]
This was caused by 3520cab1253a2e2a2caafe53eea87883bee2c1ed.
