### ISSUE TITLE
Is this project supposed to build the file chargen.bin for the x16-emulator?

### ISSUE THREAD

**Issue by simonsunnyboy** [commanderx16/x16-rom#9]
If yes, what is the make target? Typing "make" does not produce any chargen.bin for me.
If not, please add missing documentation and tell where to find the file instead.
[makelog.txt](https://github.com/commanderx16/x16-rom/files/3613600/makelog.txt)

**Comment by mist64** [comment]
The README explains it. Well, used to, until 5 minutes ago, because in the current version, chargen isn't needed any more. (It requires a manually built ROM though; or wait for the ROM bundled with the r31 release packages.)
