### ISSUE TITLE
FRE(0) hangs

### ISSUE THREAD

**Issue by EgonOlsen71** [commanderx16/x16-rom#92]
In r34, the FRE(...) function doesn't work. It doesn't return but constantly spams the console output with "invalid register ..." messages.

**Comment by mobluse** [comment]
`?FRE(0)` works for me in r34 and coming r35.

**Comment by EgonOlsen71** [comment]
Yes, it seems to work for me as well when I just start the emulator. But when I load a program in advance with -prg and then do a ?FRE(0), it hangs.

**Comment by mobluse** [comment]
Yes, I can confirm that with `x16emu -prg 10lineadv.prg`.

**Comment by mist64** [comment]
The `-prg` codepath is completely different now. Instead of injecting the code into RAM and hacking up BASIC's accounting, it goes through the KERNAL's IEEE API.

Is this fixed?

**Comment by mist64** [comment]
Probably.
