### ISSUE TITLE
Feature Request: Read current keyboard state

### ISSUE THREAD

**Issue by MJoergen** [commanderx16/x16-rom#97]
I would like to be able to read the current state of the keyboard, i.e. which key or keys are currently pressed. This feature is particularly useful in platform games.

The PS/2 protocol is event based rather than stateful, so it does not directly support this feature. This will therefore have to be emulated in the kernal.

The current GET$ function only gives information about when a key is pressed, but not when the key is released again.

I imagine a new function KEY() which takes a key (scancode?) as argument, and returns true or false depending on whether this key is currently pressed.

**Comment by mist64** [comment]
You can use the existing joystick API to get the state of the cursor keys, ctrl, alt, space and enter. If there is no NES/SNES joystick attached, the first joystick returns the state of these keys instead.

10 PRINTJOY(1):RUN

Wouldn't this be enough?

**Comment by MJoergen** [comment]
Yes, for gaming it seems adequate with the joystick API. I'm therefore closing this issue again.
